module Clients
  class SmartyClient
    CANDIDATES: int
    HEADERS: Hash[String, String]
    STREET_ADDRESS_URI: String

    @parsed_response: Array[Hash[Symbol, String]]?
    @http: Net::HTTP
    @uri: URI::Generic

    @url_string: String?

    def validate_addresses: -> Array[Models::Address]

    def clear_parsed_response!: -> void

    private

    def build_address: -> Models::Address

    def http: -> Net::HTTP

    def meets_requirements?: -> bool

    def request: -> Net::HTTP::Post

    def uri: -> URI::Generic

    def url_string: -> String

    def parsed_response: -> Array[Hash[Symbol, String]]
  end
end
