#!/usr/bin/env ruby
# frozen_string_literal: true

require "auth/authorizer"
require "bundler/setup"
require "address/valid8r"
require "dotenv"
require "optparse"

Dotenv.load

options = {}

gem_spec = Gem::Specification.load("address-valid8r.gemspec")

begin
  OptionParser.new do |opts|
    opts.banner = "Usage: #{gem_spec.name} [options]"
    opts.define_head gem_spec.summary
    opts.separator ""
    opts.on("-f", "--file [file/path/to/csv]", "absolute file path to your csv of addresses") do |file|
      options[:file] = file
    end

    opts.on("-r", "--reset", "reset your auth id, auth token, and license type") do
      options[:reset] = true
      puts "clearing environment variables"
    end
  end.parse!

  Authorizer.reset if options[:reset]
  Authorizer.authorize

  if options[:file].nil? && options[:reset]
    puts "Auth values have been set."
  elsif options[:file].nil? && options[:reset].nil?
    raise OptionParser::MissingArgument if options[:file].nil?
  else
    Address::Valid8r.process(options[:file])
  end
rescue OptionParser::MissingArgument
  puts "File Path is Required. Run #{File.basename($PROGRAM_NAME)} --help for guidance."
  exit 1
end
